### ISSUE TITLE
Unable to add the same user to multiple groups

### ISSUE THREAD

**Issue by huntastikus** [zabbix-tooling/zabbix-ldap-sync#30]
Noticing that this should now be working, I tried to add a user to multiple groups. I am receiving the following error:
```
2021-04-15 15:07:36,146 - ZabbixConn - INFO - Connected to Zabbix API Version 5.2.6
2021-04-15 15:07:36,357 - ZabbixConn - INFO - Updating user "hicklc", adding to group "Zabbix ePC Operators"
Traceback (most recent call last):
  File "./zabbix-ldap-sync", line 102, in <module>
    main()
  File "./zabbix-ldap-sync", line 98, in main
    zabbix_conn.sync_users()
  File "/root/zabbix-ldap-sync/lib/zabbixconn.py", line 395, in sync_users
    self.update_user(each_user, zabbix_group_id)
  File "/root/zabbix-ldap-sync/lib/zabbixconn.py", line 222, in update_user
    userid = self.get_user_id(user['alias'])
TypeError: string indices must be integers
```

We are running the latest version of Zabbix (5.2.6) and I installed all requirements. Importing the same user to only 1 group works without issues.

**Comment by huntastikus** [comment]
I left out that the backend is Active directory and we have tested with multiple users, the error is the same.

**Comment by scoopex** [comment]
I will have a look at this issue at weekend.

**Comment by scoopex** [comment]
I think i fixed that problem, please reopen with detailed information about your configuration and your ldap structure if you still experience problems.
