### ISSUE TITLE
Adding media to newly created user fails

### ISSUE THREAD

**Issue by Zimeon-** [zabbix-tooling/zabbix-ldap-sync#31]
We've noticed an issue with Zabbix Server 5.0.8 and ldap-sync where a newly created user won't get the specified media entry added.

Error in question;

2021-04-21 15:48:00,967 - INFO    - pyzabbix:65 - JSON-RPC Server Endpoint: https://zabbix.url/api_jsonrpc.php
2021-04-21 15:48:01,084 - INFO    - ZabbixConn:69 - Connected to Zabbix API Version 5.0.8
2021-04-21 15:48:01,118 - INFO    - ZabbixConn:309 - Creating Zabbix group ZabbixGroup
2021-04-21 15:48:01,155 - INFO    - ZabbixConn:312 - Group ZabbixGroup created with groupid 41
2021-04-21 15:48:01,288 - INFO    - ZabbixConn:393 - Updating user "user@emailaddress.com", adding to group "ZabbixGroup"
2021-04-21 15:48:03,480 - INFO    - ZabbixConn:376 - Created user seconduser@emailaddress.com and membership of Zabbix group >>ZabbixGroup<<
2021-04-21 15:48:04,095 - INFO    - ZabbixConn:423 - Add media only on newly created users for group >>>ZabbixGroup<<<
2021-04-21 15:48:04,096 - INFO    - ZabbixConn:440 - >>> Updating/create user media for "user@emailaddress.com", update "Email (HTML)"
Traceback (most recent call last):
  File "zabbix-ldap-sync", line 103, in <module>
    main()
  File "zabbix-ldap-sync", line 99, in main
    zabbix_conn.sync_users()
  File "/etc/zabbix/zabbix-ldap-sync/zabbix-ldap-sync/lib/zabbixconn.py", line 441, in sync_users
    self.update_media(each_user, self.media_name, sendto, media_opt_filtered)
  File "/etc/zabbix/zabbix-ldap-sync/zabbix-ldap-sync/lib/zabbixconn.py", line 253, in update_media
    mediatypeid = self.get_mediatype_id(description)
  File "/etc/zabbix/zabbix-ldap-sync/zabbix-ldap-sync/lib/zabbixconn.py", line 99, in get_mediatype_id
    raise Exception(f"Ambiguous media found, {len(result)} different medias")
Exception: Ambiguous media found, 0 different medias

configuration file for ldap contains the following;

[media]
description = Email
severity = Disaster, High, Average, Warning
active = 0
period = 1-7,00:00-24:00
onlycreate = true

It seems that the scripts tries to update the first use to be synced, and fails. Also the media type description doesn't seem to match the configured media type description.

**Comment by scoopex** [comment]
It seems that there is no media type "Email" in your zabbix setup.
I improved the error output to help users to get a better idea whats going wrong.

**Comment by Zimeon-** [comment]
Actually we do, named "Email"

![image](https://user-images.githubusercontent.com/5903318/115617896-a5ac7a80-a2fa-11eb-9c5d-eeadaf94496f.png)

**Comment by scoopex** [comment]
That's strange. I do not have access to a zabbix 5.0 setup.
Your error output  references a mail resource "Email (HTML)" and you config references the "description = Email".
I think you just should rename "description = Email" to "name = Email".
