### ISSUE TITLE
Issue with Zabbix 6.0

### ISSUE THREAD

**Issue by sebastianbaron** [zabbix-tooling/zabbix-ldap-sync#46]
Hello, while we we're using this solution flawlessly in Zabbix 5.0, as soon as we upgraded to 6.0 it stopped working.

The given error is as follows:

[zabbix_prod@033 ~]$ /opt/sync-ad-ldap/zabbix-ldap-sync -sd -f /opt/sync-ad-ldap/zabbix-ldap.conf

2022-05-02 11:11:59 - INFO    - pyzabbix:68 - JSON-RPC Server Endpoint: [http://10.0.0.23/zabbix//api_jsonrpc.php](http://10.0.0.23/zabbix/api_jsonrpc.php)

2022-05-02 11:11:59 - INFO    - pyzabbix:75 - Zabbix API version is: 6.0.3

2022-05-02 11:11:59 - INFO    - ZabbixConn:68 - Connected to Zabbix API Version 6.0.3

Traceback (most recent call last):

  File "/opt/sync-ad-ldap/zabbix-ldap-sync", line 115, in <module>

    main()

  File "/opt/sync-ad-ldap/zabbix-ldap-sync", line 111, in main

    zabbix_conn.sync_users()

  File "/opt/sync-ad-ldap/lib/zabbixconn.py", line 338, in sync_users

    zabbix_all_users = self.get_users()

  File "/opt/sync-ad-ldap/lib/zabbixconn.py", line 80, in get_users

    users = [user['alias'] for user in result]

  File "/opt/sync-ad-ldap/lib/zabbixconn.py", line 80, in <listcomp>

    users = [user['alias'] for user in result]

KeyError: 'alias'

Any ideas on what it could be?

**Comment by scoopex** [comment]
That seems to valid. It seems that there is a wrong version comparison from a former pull request.

I made a quick improvement, probably this helps you :-) I do not have Zabbix 6 with a configured ldap sync. 
https://github.com/zabbix-tooling/zabbix-ldap-sync/commit/b819f4c0b386cf4f5c2ff06c0bb40806df36ccf0

Can you provide feedback i your problem is solved now?

**Comment by sebastianbaron** [comment]
**So we tried and it failed as follows:**

2022-05-09 15:51:41 - INFO    - ZabbixConn:104 - Connected to Zabbix API Version 6.0.3

Traceback (most recent call last):

  File "/home/NET01/vtclusar/zabbix-ldap-sync-master/zabbix-ldap-sync", line 115, in <module>

   main()

  File "/home/NET01/vtclusar/zabbix-ldap-sync-master/zabbix-ldap-sync", line 109, in main

   zabbix_conn.connect()

  File "/home/NET01/vtclusar/zabbix-ldap-sync-master/lib/zabbixconn.py", line 105, in connect

   if float(self.conn.api_version()) > 5.2:

ValueError: could not convert string to float: '6.0.3'

**So, as we are only using Zabbix 6 we forced the self.username_attribute = 'username' and got this:**

2022-05-09 17:20:23 - INFO    - pyzabbix:75 - Zabbix API version is: 6.0.3

2022-05-09 17:20:23 - INFO    - ZabbixConn:104 - Connected to Zabbix API Version 6.0.3

2022-05-09 17:20:24 - INFO    - ZabbixConn:408 - Creating Zabbix group GS.view_zabbix

2022-05-09 17:20:24 - INFO    - ZabbixConn:411 - Group GS.view_zabbix created with groupid 15

2022-05-09 17:20:24 - INFO    - ZabbixConn:461 - Processing group >>>GS.view_zabbix<<<...

Traceback (most recent call last):

  File "/home/NET01/vtclusar/zabbix-ldap-sync-master/zabbix-ldap-sync", line 115, in <module>

   main()

  File "/home/NET01/vtclusar/zabbix-ldap-sync-master/zabbix-ldap-sync", line 111, in main

   zabbix_conn.sync_users()

  File "/home/NET01/vtclusar/zabbix-ldap-sync-master/lib/zabbixconn.py", line 467, in sync_users

   ldap_users = {k.lower(): v for k, v in self.ldap_conn.get_group_members(group_name).items()}

  File "/home/NET01/vtclusar/zabbix-ldap-sync-master/lib/ldapconn.py", line 100, in get_group_members

   return self.get_group_members_active_directory(result)

  File "/home/NET01/vtclusar/zabbix-ldap-sync-master/lib/ldapconn.py", line 187, in get_group_members_active_directory

   attrlist=attrlist)

  File "/var/lib/zabbix/pyzbx/lib64/python3.6/site-packages/ldap/ldapobject.py", line 631, in search_s

   return self.search_ext_s(base,scope,filterstr,attrlist,attrsonly,None,None,timeout=self.timeout)

  File "/var/lib/zabbix/pyzbx/lib64/python3.6/site-packages/ldap/ldapobject.py", line 624, in search_ext_s

   msgid = self.search_ext(base,scope,filterstr,attrlist,attrsonly,serverctrls,clientctrls,timeout,sizelimit)

  File "/var/lib/zabbix/pyzbx/lib64/python3.6/site-packages/ldap/ldapobject.py", line 620, in search_ext

   timeout,sizelimit,

  File "/var/lib/zabbix/pyzbx/lib64/python3.6/site-packages/ldap/ldapobject.py", line 128, in _ldap_call

   result = func(*args,**kwargs)

ldap.FILTER_ERROR: {'result': -7, 'desc': 'Bad search filter', 'ctrls': []}

**Comment by vanimesh** [comment]
Is this solved ? I am also getting the same error as below, when used with zabbix 6.0. Seems like the group is created but the users are not.

ldap.FILTER_ERROR: {'result': -7, 'desc': 'Bad search filter', 'ctrls': []}
