### ISSUE TITLE
zabbix version check problem

### ISSUE THREAD

**Issue by kkmaslowski** [zabbix-tooling/zabbix-ldap-sync#47]
Hi. 
Script output on latest version:

```
2022-05-09 09:05:14 - INFO    - pyzabbix:75 - Zabbix API version is: 4.4.10
2022-05-09 09:05:14 - INFO    - ZabbixConn:104 - Connected to Zabbix API Version 4.4.10
Traceback (most recent call last):
  File "./zabbix-ldap-sync", line 115, in <module>
    main()
  File "./zabbix-ldap-sync", line 109, in main
    zabbix_conn.connect()
  File "/opt/zabbix-ldap-sync/lib/zabbixconn.py", line 105, in connect
    if float(self.conn.api_version()) > 5.2:
```

Please also reopen my previous issue: https://github.com/zabbix-tooling/zabbix-ldap-sync/issues/44

**Comment by scoopex** [comment]
Repaired that now, i am sorry :-)
