### ISSUE TITLE
zabbix version value (ValueError)

### ISSUE THREAD

**Issue by robbyleh** [zabbix-tooling/zabbix-ldap-sync#48]
Hello, 

following problem I have. I don't have an idea how to work around this. 
# ./zabbix-ldap-sync -n  -f zabbix-ldap-user.conf
2022-05-13 17:36:00 - INFO    - ZabbixLDAPConf:41 - configuration for zabbix-ldap-sync release 0.13
2022-05-13 17:36:01 - INFO    - pyzabbix:68 - JSON-RPC Server Endpoint: http://localhost/zabbix//api_jsonrpc.php
2022-05-13 17:36:01 - INFO    - pyzabbix:75 - Zabbix API version is: 5.0.15
2022-05-13 17:36:01 - INFO    - ZabbixConn:104 - Connected to Zabbix API Version 5.0.15
Traceback (most recent call last):
  File "./zabbix-ldap-sync", line 115, in <module>
    main()
  File "./zabbix-ldap-sync", line 109, in main
    zabbix_conn.connect()
  File "/opt/zabbix/zabbix-ldap-sync/lib/zabbixconn.py", line 105, in connect
    if float(self.conn.api_version()) > 5.2:
ValueError: could not convert string to float: '5.0.15'
[root@dcfra-vision-vi-zbx-srv1 zabbix-ldap-sync]#

Thanks in advance

**Comment by scoopex** [comment]
I am really sorry, i repaired that now.
