### ISSUE TITLE
requests.exceptions.SSLError

### ISSUE THREAD

**Issue by robbyleh** [zabbix-tooling/zabbix-ldap-sync#49]
Hi , 

thank you for the quick fix last week.
I just enabled https now for the Zabbix API as this is required in our production environment.
Now I get :

[root@servername zabbix-ldap-sync]# ./zabbix-ldap-sync -n -f zabbix-ldap-AD-Group-Name.conf
2022-05-17 15:23:10 - INFO    - ZabbixLDAPConf:41 - configuration for zabbix-ldap-sync release 0.13
2022-05-17 15:23:10 - INFO    - pyzabbix:68 - JSON-RPC Server Endpoint: https://zabbix-server-url/zabbix//api_jsonrpc.php
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 358, in connect
    ssl_context=context)
  File "/usr/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 354, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.6/ssl.py", line 365, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib64/python3.6/ssl.py", line 776, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1036, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 648, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='zabbix-server-url', port=443): Max retries exceeded with url: /zabbix//api_jsonrpc.php (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),))

Even if I set ignore_tls_errors = true , same issue...
I miss the "verify=False" option in the section Zabbix.
I haven't neither  a glue how to turn this off on the lower system level. 
For ldaps it is ldap.conf but I'm not sure how to do for the API https requests.

Thanks in advance,
Rob

**Comment by robbyleh** [comment]
ahh and even if I start with -n I'll see the same outcome... (./zabbix-ldap-sync -n -f ...)

**Comment by robbyleh** [comment]
It seems that SSL is not working at all in python. maybe... Still try to find the root cause here...
Some more details:
Red Hat Enterprise Linux 8.6 (Ootpa)
openssl-1.1.1k
Python 3.6.8

**Comment by robbyleh** [comment]
Hi, 

as far as I understand the release notes of openssl SSLvX is no longer available since version 1.1.1.
I'm not sure how I can see if your code attempts to use SSLvX or TLS, but reading the error message it looks like SSL (_ssl.c:897)
My old Zabbix installation was running on CentOS7 and ldap-syncc was running fine.
So this is just a guess and a question...
Thansk in advance, 
Robby

**Comment by p3l1** [comment]
Not directely related to your issue, but take into account for Zabbix 6.2 improvements for LDAP and AD authentication are planned. The feature is currently in design phase, see https://www.zabbix.com/roadmap

> Support automatic user creation after successful AD, LDAP, or SAML authentication. It will allow remote management of users and their permissions

Maybe wait and see what features are added in Zabbix 6.2. and if this script is still needed then.

**Comment by blodone** [comment]
the SSL issue is not related to our code as the libs of the underlying connections are not working together.
we can disable verify with the "ignore_tls_errors" option that is equal to verify=False but when no handshake at all is established there is nothing to be verified
