### ISSUE TITLE
Creating user in zabbix from AD when surname is empty

### ISSUE THREAD

**Issue by craviee** [zabbix-tooling/zabbix-ldap-sync#5]
When an user in AD has empty surname, the program generate an AttributeError:

Traceback (most recent call last):
  File "./zabbix-ldap-sync", line 92, in <module>
    main()
  File "./zabbix-ldap-sync", line 89, in main
    zabbix_conn.sync_users()
  File "/root/zabbix-ldap-sync/lib/zabbixconn.py", line 369, in sync_users
    user['surname'] = self.ldap_conn.get_user_sn(ldap_users[eachUser]).decode('utf8')
AttributeError: 'NoneType' object has no attribute 'decode'

**Comment by craviee** [comment]
#6 fixed this issue.
