### ISSUE TITLE
Exception: Ambiguous media 'Email' found, 7 different medias

### ISSUE THREAD

**Issue by kkmaslowski** [zabbix-tooling/zabbix-ldap-sync#51]
On some accounts I got error message like above. When I run script again there is no error.

```
2022-05-31 14:57:30 - INFO    - ZabbixConn:592 - >>> Updating/create user media for "user@domain.local", update "Email"
Traceback (most recent call last):
  File "./zabbix-ldap-sync", line 115, in <module>
    main()
  File "./zabbix-ldap-sync", line 111, in main
    zabbix_conn.sync_users()
  File "/opt/zabbix-ldap-sync/lib/zabbixconn.py", line 593, in sync_users
    self.update_media(each_user, self.media_name, sendto, media_opt_filtered)
  File "/opt/zabbix-ldap-sync/lib/zabbixconn.py", line 353, in update_media
    mediatypeid = self.get_mediatype_id(description)
  File "/opt/zabbix-ldap-sync/lib/zabbixconn.py", line 154, in get_mediatype_id
    raise Exception(f"Ambiguous media '{name}' found, {len(result)} different medias")
Exception: Ambiguous media 'Email' found, 7 different medias
```

Zabbix server version: 4.0
Media configuration:
```
[media]
name = Email
severity = Disaster,High,Average,Warning
period = 1-7,00:07-22:00
# 1=disabled, 0=enabled
active = 0
onlycreate = true
```

**Comment by blodone** [comment]
seems like you configured more then one "Email" Media type in zabbix. currently only one relation with the same media type naming is supported

**Comment by kkmaslowski** [comment]
@blodone 
I have one media with type Email. All other 6 medias are Scripts and SMS.

**Comment by scoopex** [comment]
Please provide a list of the names of your Medias.

**Comment by scoopex** [comment]
No response, closing the problem.
Please reopen after submitting the infromation.

**Comment by kkmaslowski** [comment]
@scoopex: sorry for delay.

My all media types:
- Email	Email	Enabled
- Jabber	Jabber
- Maintenance	Script	Enabled
- SMS	SMS	Disabled	
- SMS-gnokii	Script	Disabled
- Telegram	Script	Enabled	
- Telegram Group	Script	Enabled

I have the same problem on my second Zabbix server with the following media types:
- 	Email	Email	Enabled
- 	Jabber	Jabber	Disabled
- 	Maintenance	Script	Enabled
- 	SMS	SMS	Disabled

Log for second server:
```
2023-01-12 06:30:00 - INFO    - pyzabbix:75 - Zabbix API version is: 4.0.44
2023-01-12 06:30:00 - INFO    - ZabbixConn:115 - Connected to Zabbix API Version 4.0.44
...
2023-01-12 06:30:05 - INFO    - ZabbixConn:563 - Updating media for users...
2023-01-12 06:30:05 - INFO    - ZabbixConn:577 - Add media only on newly created users for group >>>DEV<<<
2023-01-12 06:30:05 - INFO    - ZabbixConn:595 - >>> Updating/create user media for "somelogin@mydomain.local", update "Email"
Traceback (most recent call last):
  File "/opt/zabbix-ldap-sync/zabbix-ldap-sync", line 115, in <module>
    main()
  File "/opt/zabbix-ldap-sync/zabbix-ldap-sync", line 111, in main
    zabbix_conn.sync_users()
  File "/opt/zabbix-ldap-sync/lib/zabbixconn.py", line 596, in sync_users
    self.update_media(each_user, self.media_name, sendto, media_opt_filtered)
  File "/opt/zabbix-ldap-sync/lib/zabbixconn.py", line 356, in update_media
    mediatypeid = self.get_mediatype_id(description)
  File "/opt/zabbix-ldap-sync/lib/zabbixconn.py", line 157, in get_mediatype_id
    raise Exception(f"Ambiguous media '{name}' found, {len(result)} different medias")
Exception: Ambiguous media 'Email' found, 4 different medias

```
