### ISSUE TITLE
Correct LDAP Credentials and Validated but getting error ldap.INVALID_CREDENTIALS

### ISSUE THREAD

**Issue by chezterchan** [zabbix-tooling/zabbix-ldap-sync#53]
Hello,
I was able to install all dependencies and ran my first sync how error, I am getting an invalid credentials error. I know that the credential is correct since I used it to create the LDAP bind on Zabbix portal. Is there a restriction as to what type of characters are allowed on the ldap password entry?

Full STDERR:
Traceback (most recent call last):
  File "./zabbix-ldap-sync", line 115, in <module>
    main()
  File "./zabbix-ldap-sync", line 107, in main
    ldap_conn.connect()
  File "/home/myuser/zabbix-ldap-sync/lib/ldapconn.py", line 57, in connect
    self.conn.simple_bind_s(self.ldap_user, self.ldap_pass)
  File "/root/.local/lib/python3.6/site-packages/ldap/ldapobject.py", line 249, in simple_bind_s
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,timeout=self.timeout)
  File "/root/.local/lib/python3.6/site-packages/ldap/ldapobject.py", line 546, in result3
    resp_ctrl_classes=resp_ctrl_classes
  File "/root/.local/lib/python3.6/site-packages/ldap/ldapobject.py", line 553, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/root/.local/lib/python3.6/site-packages/ldap/ldapobject.py", line 128, in _ldap_call
    result = func(*args,**kwargs)
ldap.INVALID_CREDENTIALS: {'msgtype': 97, 'msgid': 1, 'result': 49, 'desc': 'Invalid credentials', 'ctrls': [], 'info': '80090308: LdapErr: DSID-0C090439, comment: AcceptSecurityContext error, data 52e, v4563'}

**Comment by scoopex** [comment]
No, there is no restriction.
"INVALID_CREDENTIALS" suggests that there is something wrong with our account. Test your connection with a ldap browser tool (see https://github.com/zabbix-tooling/zabbix-ldap-sync/blob/master/README.md#config-file-sections).
