### ISSUE TITLE
Not working with zabbix 6.0

### ISSUE THREAD

**Issue by vanimesh** [zabbix-tooling/zabbix-ldap-sync#54]
Hi @blodone , i am getting the below error while trying it with zabbix 6

 Seems like the group is created but the users are not.

ldap.FILTER_ERROR: {'result': -7, 'desc': 'Bad search filter', 'ctrls': []}

**Comment by vanimesh** [comment]
2022-11-03 14:03:42 - INFO    - ZabbixLDAPConf:41 - configuration for zabbix-ldap-sync release [unknown, no sourcecode checkout]
2022-11-03 14:03:42 - INFO    - pyzabbix:68 - JSON-RPC Server Endpoint: http://10.121.22.108:8080//api_jsonrpc.php
2022-11-03 14:03:44 - INFO    - pyzabbix:75 - Zabbix API version is: 6.0.9
2022-11-03 14:03:45 - INFO    - ZabbixConn:115 - Connected to Zabbix API Version 6.0.9
2022-11-03 14:03:48 - INFO    - ZabbixConn:474 - Processing group >>>APP-Zabbix_Admin<<<...
Traceback (most recent call last):
  File "./ldapSync", line 115, in <module>
    main()
  File "./ldapSync", line 111, in main
    zabbix_conn.sync_users()
  File "/u01/app/zabbix/lib/zabbixconn.py", line 478, in sync_users
    ldap_users = {k: v for k, v in self.ldap_conn.get_group_members(group_name).items()}
  File "/u01/app/zabbix/lib/ldapconn.py", line 100, in get_group_members
    return self.get_group_members_active_directory(result)
  File "/u01/app/zabbix/lib/ldapconn.py", line 184, in get_group_members_active_directory
    uid = self.conn.search_s(base=member.decode('utf8'),
  File "/u01/app/zabbix/venv/lib64/python3.8/site-packages/ldap/ldapobject.py", line 631, in search_s
    return self.search_ext_s(base,scope,filterstr,attrlist,attrsonly,None,None,timeout=self.timeout)
  File "/u01/app/zabbix/venv/lib64/python3.8/site-packages/ldap/ldapobject.py", line 624, in search_ext_s
    msgid = self.search_ext(base,scope,filterstr,attrlist,attrsonly,serverctrls,clientctrls,timeout,sizelimit)
  File "/u01/app/zabbix/venv/lib64/python3.8/site-packages/ldap/ldapobject.py", line 614, in search_ext
    return self._ldap_call(
  File "/u01/app/zabbix/venv/lib64/python3.8/site-packages/ldap/ldapobject.py", line 128, in _ldap_call
    result = func(*args,**kwargs)
**ldap.FILTER_ERROR: {'result': -7, 'desc': 'Bad search filter', 'ctrls': []}**

**Comment by vanimesh** [comment]
@blodone any update ? Pls help here

**Comment by blodone** [comment]
@vanimesh it's saying your search filter is bad. That means you specified some wrong value in the user_filter or in the disabled_filter.

I'm using this with zabbix 6.2 so there is nothing wrong with the script at this point

**Comment by vanimesh** [comment]
Thank you @blodone  for showing hope...😊.Can you please help me where to find those ? user_filter and disabled_filter please. Please lete know if you need any config files.

**Comment by vanimesh** [comment]
@blodone , below is my config file

[ldap]
type = activedirectory
uri = ldaps://ldap.uat.com:636/
base = OU=Corporate,DC=uat,DC=uat,DC=com
binduser = zabbix_ro
bindpass = asdfghjklwertyui
groups = APP-Zabbix_Admin

[ad]
filtergroup = (&(objectClass=group)(name=%s))
filteruser = (objectClass=user)(objectCategory=Person)
filterdisabled = (!(userAccountControl:1.2.840.113556.1.4.803:=2))
filtermemberof = (memberOf:1.2.840.113556.1.4.1941:=%s)
groupattribute = member
userattribute = sAMAccountName

[openldap]
type = posix
filtergroup = (&(objectClass=posixGroup)(cn=%s))
filteruser = (&(objectClass=posixAccount)(uid=%s))
groupattribute = memberUid
userattribute = uid

[zabbix]
server = http://10.211.221.108:8080/
username = Admin
password = zabbix
auth = webform

[user]
role =Admin role

**Comment by scoopex** [comment]
Use a ldap client like Apache Directory Studio to test the ldap connection, filters and to inspect available attributes.
The flag --verbose helps to get the ldap filters calculated by the script.
